# Generated by Django 5.1.2 on 2024-10-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Front-end', 'Front-end'), ('Back-end', 'Back-end'), ('Android', 'Android'), ('iOS', 'iOS')], max_length=15)),
            ],
        ),
    ]
